version: '3'
services:
  app:
    container_name: blog_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - goblog-postgres
    networks:
      - goblog
  goblog-postgres:
    image: postgres:latest
    container_name: blog_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - goblog

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - goblog-postgres
    ports:
      - "5050:80"
    networks:
      - goblog
    restart: unless-stopped


volumes:
  api:
  database_postgres:                  # Uncomment this when using postgres.

networks:
  goblog:
    driver: bridge