apiVersion: v1
kind: Service
metadata:
  name: goblog-postgres
  labels:
    app: goblog-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: goblog-postgres
    title: postgres
